name: Build and Validate Internet-Draft

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mmark
        run: |
          go install github.com/mmarkdown/mmark@latest

      - name: Install xml2rfc
        run: |
          pip install xml2rfc

      - name: Convert Markdown to XML (using mmark)
        run: |
          # Assuming the draft is versioned at 00
          mmark draft-sweetser-bcp-rpki-ca-00.md > draft-sweetser-bcp-rpki-ca-00.xml

      - name: Generate IETF formats (using xml2rfc)
        run: |
          xml2rfc --text --html --verbose draft-sweetser-bcp-rpki-ca-00.xml

      - name: Validate XML (maybe add ISDITS later?)
        run: |
          xml2rfc --strict draft-sweetser-bcp-rpki-ca-00.xml

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ietf-draft-outputs
          path: |
            draft-sweetser-bcp-rpki-ca-00.xml
            draft-sweetser-bcp-rpki-ca-00.txt
            draft-sweetser-bcp-rpki-ca-00.html